function ReadEDSFiles

clc
close all
clear all

scrsz = get(0,'ScreenSize');

figPercent = 0.85; % Percent of screen that the figure occupies
figLR = ((1-figPercent)/2)*scrsz(3);
figBot = ((1-figPercent)/2)*scrsz(4);
figW = figPercent*scrsz(3);
figH = figPercent*scrsz(4);

figPosition = [figLR figBot figW figH];
 
fig1 = figure('Color','w','Position',figPosition,'name','EDS_Reader');

uicontrol('Parent',fig1,'Style','pushbutton','String', 'Load EDS Folder',...
     'Tag','PickFilePath',...
    'Units','Normalized','Position',[0 .9 0.09 0.05],...
    'Callback',{@PickFilePathAndReadData,figPosition});

uicontrol('Parent',fig1,'Style','popupmenu','String', {' '},...
    'Tag','DataUnits',...
    'Units','Normalized','Position',[0 .8 0.09 0.05],...
    'Callback',{@DataUnits,figPosition});

uicontrol('Parent',fig1,'Style','togglebutton','String', 'Choose Elements',...
    'Tag','ChooseElements',...
    'Units','Normalized','Position',[0 .7 0.09 0.05],...
    'Callback',@ChooseElementsBut);

uicontrol('Parent',fig1,'Style','pushbutton','String', 'Element Mapping',...
    'Tag','ColoredMaps',...
    'Units','Normalized','Position',[0 .6 0.09 0.05],...
    'Callback',{@ColoredMapsBut,figPosition});

uicontrol('Parent',fig1,'Style','pushbutton','String', 'Oxidation Mapping',...
    'Tag','OxideMapping',...
    'Units','Normalized','Position',[0 .5 0.09 0.05],...
    'Callback',{@OxideMappingBut,figPosition});

uicontrol('Parent',fig1,'Style','pushbutton','String', 'Threshold Mapping',...
    'Tag','ThresholdMapping',...
    'Units','Normalized','Position',[0 .4 0.09 0.05],...
    'Callback',{@ThresholdMappingBut,figPosition});


uicontrol('Parent',fig1,'Style','togglebutton','String', 'Draw ROI',...
    'Tag','DrawROI',...       
    'Units','Normalized','Position',[.91 .8 0.09 0.05],...
    'Callback',@DrawBut);

uicontrol('Parent',fig1,'Style','togglebutton','String', 'Draw Line',...
    'Tag','DrawLine',...    
    'Units','Normalized','Position',[.91 .7 0.09 0.05],...
    'Callback',@DrawLineBut);

uicontrol('Parent',fig1,'Style','togglebutton','String', 'Zoom',...
    'Tag','ZoomDrag',...
    'Units','Normalized','Position',[.91 .6 0.09 0.05],...
    'Callback',@ZoomDragBut);

uicontrol('Parent',fig1,'Style','pushbutton','String', 'Full View',...
    'Tag','FullView',...   
    'Units','Normalized','Position',[.91 .5 0.09 0.05],...
    'Callback',@FullViewBut);

uicontrol('Parent',fig1,'Style','text','String', 'ROI List:','BackgroundColor','w',...
    'HorizontalAlignment','Left','Units','Normalized','Position',[.91 .44 0.08 0.03]);

uicontrol('Parent',fig1,'Style','popupmenu','String', 'Empty',...
    'Tag','ROIList',...       
    'Units','Normalized','Position',[.91 .4 0.09 0.05],...
    'Callback',@PopUpMenuFnc);

uicontrol('Parent',fig1,'Style','pushbutton','String', 'Delete Selected',...
    'Tag','DeleteROI',...       
    'Units','Normalized','Position',[.91 .38 0.08 0.03],...
    'Callback',@DeleteBut);

uicontrol('Parent',fig1,'Style','pushbutton','String', 'Analyze ROIs',...
    'Tag','AnalyzeROIs',...       
    'Units','Normalized','Position',[.91 .3 0.09 0.05],...
    'Callback',{@AnalyzeROIsFnc,figPosition});